<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>js中内建对象之error对象</title>
</head>
<body>
	<script type="text/javascript">
		// try{
		// 	notExists();
		// }catch(e){
		// 	alert(e.name+':'+e.message)
		// }
		// try{
		// 	var n = 2;
		// 	if(n==0){
		// 		throw new Error('0不能当做除数');
		// 	}else{
		// 		alert(4/n);
		// 	}
		// }catch(e){
		// 	alert(e.name+':'+e.message);
		// }finally{
		// 	alert('我总是被调用');
		// }
		// try{
		// 	notExists();
		// }catch(e){
		// 	if(e instanceof EvalError){
		// 		alert('Eval错误'+e.message);
		// 	}else if(e instanceof RangeError){
		// 		alert('Range错误'+e.message);
		// 	}else if(e instanceof TypeError){
		// 		alert('Type错误'+e.message);
		// 	}else if(e instanceof ReferenceError){
		// 		alert('Reference错误'+e.message);
		// 	}else{
		// 		alert('其他错误');
		// 	}
		// }
		//自定义错误
		// function MyError(msg){
		// 	this.name = 'MyError'
		// 	this.message = msg||'默认的自定义错误信息';
		// }
		// MyError.prototype = Object.create(Error.prototype);
		// MyError.prototype.constructor = MyError;
		// try{
		// 	throw new MyError();
		// }catch(e){
		// 	console.log(e.name+':'+e.message);
		// }

		// try{
		// 	throw new MyError('测试自定义的错误信息');
		// }catch(e){
		// 	console.log(e.name+':'+e.message);
		// }

		var o1 = {x:1};
		var o2 = {x:1};
		console.log(o1==o2);
		var o3 = {x:1};
		var o4 = o3;
		o4.x = 123;
		console.log(o3.x);

		function f(o){
			o.x = 55;
		}
		f(o3);
		console.log(o4.x);
		console.log(o3===o4);
	</script>
</body>
</html>